apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: argocd
  name: argocd-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: argocd-ingress

spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: argocd-server
            servicePort: 80
